### ISSUE TITLE
JSON parsing issue

### ISSUE THREAD

**Issue by fcrbe** [signalfx/signalfx-nodejs-tracing#52]
We see the below trace being thrown on a daily basis and I'm running out of clues why we have this issue. Seems like some HTML being retrieved where JSON is expected (maybe because the signalfx agent is down, although we have no indications of that), however, I assume this should be catched somewhere in signalfx-tracing?

![image](https://user-images.githubusercontent.com/14942750/78277932-9141e800-7515-11ea-8fd0-c5eae86df48d.png)

**Comment by rmfitzpatrick** [comment]
@fcrbe this is the error handler of the `tracer.scope().activate()` instrumentation function that is rethrowing a failing `JSON.parse()` after tagging the representative span with the error content.  It appears to be an issue in the application code at `/app/build/server.js:36129`.  I don't believe it's an issue with this library, though the underlying functionality of your server is being traced by it.

FMI:
https://github.com/signalfx/signalfx-nodejs-tracing/blob/master/docs/API.md#scopeactivatespan-fn
https://github.com/signalfx/signalfx-nodejs-tracing/blob/master/src/scope/new/scope.js#L50

**Comment by fcrbe** [comment]
Yep, you're right @rmfitzpatrick , thanks for pointing out. Checked the condensed server.js and found the issue!
