### ISSUE TITLE
Add "http2" support

### ISSUE THREAD

**Issue by yinzara** [signalfx/signalfx-nodejs-tracing#76]
Add support to instrument the "http2" NodeJS library (added in 8.13 and 10+)
https://nodejs.org/api/http2.html

This is used by the entire Google Cloud platform for all their provided services and would be extremely helpful.

**Comment by jtmalinowski** [comment]
Hi @yinzara, can you say if you're a customer of SignalFx / Splunk Observability? (can be over e-mail, my address is in my profile)

**Comment by jtmalinowski** [comment]
We'll be supporting `http2` in <https://github.com/signalfx/splunk-otel-js>, unless you have reasons not to migrate to Open Telemetry, in which case please let me know.
