### ISSUE TITLE
Http module patches http.reqeust in a way thats incompatable with NodeJs > v10

### ISSUE THREAD

**Issue by romansavchenko** [signalfx/signalfx-nodejs-tracing#78]
It overwrites http.request and https.request with only two arguments: options and callback, while node api > 10 provides url, options and callback.

This breaks common modern implementations like `got`  https://github.com/sindresorhus/got/issues/876#issuecomment-561096910

**Comment by jtmalinowski** [comment]
Hi @romansavchenko, I've created an internal ticket for this. Do you mind emailing me (my email is in my profile) so I know if you're a customer?

**Comment by jtmalinowski** [comment]
I think we'll need to rephrase it as support for NodeJS v12, which is the next LTS after v10. While possibly `http.request` is the only issue to be fixed, we need to be clear about which versions are supported.

**Comment by rkburnett** [comment]
Hi @jtmalinowski 
Is there any update on this issue? I am running NodeJS v12.21.0 and also running into this issue... it has turned out to be quite a blocker.

Can you also clarify what versions of NodeJS are compatible with signalfx-tracing v0.12.0 ? Thanks!

**Comment by jtmalinowski** [comment]
Hi @rkburnett, <https://github.com/signalfx/splunk-otel-js> is currently in beta, we provide support for it, and once it's 1.0, which should be soon, it'll replace `signalfx-nodejs-tracing`. I think you'll be more satisfied with it, because it's basically a small configuration layer on top of <https://github.com/open-telemetry/opentelemetry-js>. However, if you can't / don't want to switch, let me know.

**Comment by andrew-prior** [comment]
The migration link [Migrate from the SignalFx Tracing Library for JS](https://github.com/signalfx/splunk-otel-js/blob/main/migration.md) does not work.

**Comment by jtmalinowski** [comment]
@andrew-prior I'm working on it, I'll let you know when it's fixed.

**Comment by rkburnett** [comment]
@jtmalinowski Is it still a possibility to get support for Node 12 for `signalfx-tracing` to fix this issue? How long before that could be available? Thanks again for your help.

**Comment by jtmalinowski** [comment]
@rkburnett Of course, we still provide support for this library, but to start that, I'd need to open a support ticket for you (in which case please let me know which company you're at, the email address is in my profile). The problem with providing an ETA is that I can't just upgrade the `http` instrumentation to node 12+, it has to be done and tested well for all supported instrumentations - obviously I (or one of my colleagues) will do that if we open the ticket.

**Comment by rkburnett** [comment]
Is there any update on fixing the migration guide @jtmalinowski ? 
[Migrate from the SignalFx Tracing Library for JS](https://github.com/signalfx/splunk-otel-js/blob/main/migration.md)

Thanks.

**Comment by jtmalinowski** [comment]
It's going through proof-reading and testing now, we should merge the fix tomorrow or the day after.

**Comment by rkburnett** [comment]
Thanks @jtmalinowski !

**Comment by jtmalinowski** [comment]
The PR is ready to merge but I need to sync it with a release, that will happen tomorrow afternoon CET. If you'd like a sneak peak then it's here <https://github.com/signalfx/splunk-otel-js/pull/169>.

In addition to that, I'll be estimating the effort to support Node.js 12 some time next week.

**Comment by andrew-prior** [comment]
Thanks. I have read though the MR. I appreciate that you point out the "limitations" even though your colleague was a little wary of it. It helped me know what it is going to take to get feature parity with signalfx-nodejs-tracing library.

**Comment by jtmalinowski** [comment]
Guide is up now <https://github.com/signalfx/splunk-otel-js/blob/main/MIGRATING.md>. I'll be looking into support for Node.js 12 soon.

**Comment by andrew-prior** [comment]
Any estimation on what it will take to patch signalfx-nodejs-tracing to not clobber the request object.

**Comment by jtmalinowski** [comment]
@andrew-prior @rkburnett This is now in the backlog. I don't have an exact date yet, but I'd expect this to be done sometime within the next 2 weeks.

**Comment by sanknmFinicity** [comment]
@jtmalinowski Any updates on above ?

**Comment by jtmalinowski** [comment]
@sanknmFinicity right, I should have updated the issue. It's quite difficult to resolve this properly, because 1) we want to be clear about which versions are supported, and fixing this would mean committing to supporting Node.js v12, and that triggers a cascade of many necessary fixes 2) all Node.js development efforts now go towards <https://github.com/signalfx/splunk-otel-js> which supports 8.5 - latest LTS.

If switching to `@splunk/otel` doesn't work for you, email me or our tech support, we'll be resolving this on case-by-case basis.
